version: '3.9'

services:
  app:
    container_name: 'next-app'
    build:
      dockerfile: docker/develop/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./
        target: /app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
